### ISSUE TITLE
Compilation errors with 5.34.0

### ISSUE THREAD

**Issue by eserte** [tokuhirom/Perl-Lexer#11]
Please see http://matrix.cpantesters.org/?dist=Perl-Lexer+0.33 for an overview --- all builds with perl 5.34.0 result in "unknown" reports.

On a freebsd 13 system it looks like this:
```
...
cc -I. -Ilib/Perl -I/usr/perl5.34.0Dp/lib/5.34.0/amd64-freebsd-ld/CORE -DVERSION="0.33" -DXS_VERSION="0.33" -DPIC -fPIC -c -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -O2 -pipe -o temp/Lexer.o temp/Lexer.c
In file included from lib/Perl/Lexer.xs:16:
In file included from lib/Perl/gen/token_info_map.h:390:
lib/Perl/gen/token_info-5.34.0.h:66:5: warning: implicit declaration of function 'DEBUG_TOKEN' is invalid in C99 [-Wimplicit-function-declaration]
    DEBUG_TOKEN (IVAL, PERLY_AMPERSAND),
    ^
lib/Perl/gen/token_info-5.34.0.h:66:18: error: use of undeclared identifier 'IVAL'
    DEBUG_TOKEN (IVAL, PERLY_AMPERSAND),
                 ^
lib/Perl/gen/token_info-5.34.0.h:67:18: error: use of undeclared identifier 'IVAL'
    DEBUG_TOKEN (IVAL, PERLY_BRACE_CLOSE),
                 ^
lib/Perl/gen/token_info-5.34.0.h:68:18: error: use of undeclared identifier 'IVAL'
    DEBUG_TOKEN (IVAL, PERLY_BRACE_OPEN),
                 ^
... etc ...
lib/Perl/gen/token_info-5.34.0.h:82:18: error: use of undeclared identifier 'IVAL'
    DEBUG_TOKEN (IVAL, PERLY_SLASH),
                 ^
lib/Perl/gen/token_info-5.34.0.h:83:18: error: use of undeclared identifier 'IVAL'
    DEBUG_TOKEN (IVAL, PERLY_SNAIL),
                 ^
lib/Perl/gen/token_info-5.34.0.h:84:18: error: use of undeclared identifier 'IVAL'
    DEBUG_TOKEN (IVAL, PERLY_STAR),
                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
error building temp/Lexer.o from 'temp/Lexer.c' at /usr/perl5.34.0Dp/lib/5.34.0/ExtUtils/CBuilder/Base.pm line 185.
```

**Comment by syohex** [comment]
https://github.com/Perl/perl5/commit/c588171e624c7ef69a51c51bb22df460e83e6dd8#diff-eab4115a843bf91f2d20457b59e6b0c6c747ffa64ba1022d3ff958512da8df12

`DEBUG_TOKEN` macro was introduced at above commit. But `author/get_sources.pl` does not consider its macro and this causes build error. I'm not sure that the author script should extract macro or it should ignore lines which use `DEBUG_TOKEN`. 

CC: @charsbar

**Comment by charsbar** [comment]
@syohex Thanks for the info. Will take care of it later.

**Comment by charsbar** [comment]
Shipped 0.34. Thank you all.
